    /*
    This is a generated code based on DDL yaml. Please don't edit it.
    (c) Data Facade LLC.
    */
    
const ProviderParameterDefinitionId = {
    AWS_ACCESS_KEY: "23",
    AWS_SECRET_KEY: "24",
    S3_BUCKET_NAME: "21",
    S3_BUCKET_REGION: "25",
    S3_BUCKET_PATH: "22",
    POSTGRESQL_CONNECTION_URL: "26",
    POSTGRESQL_USERNAME: "27",
    POSTGRESQL_PASSWORD: "28",
    DATABRICKS_SERVER_HOSTNAME: "2",
    DATBRICKS_WORKSPACE_PAT: "1",
    DATABRICKS_HTTP_PATH: "37",
    SNOWFLAKE_PASSWORD: "5",
    SNOWFLAKE_ACCOUNT_ID: "4",
    SNOWFLAKE_WAREHOUSE: "8",
    SNOWFLAKE_DATABASE: "7",
    SNOWFLAKE_USERNAME: "6",
    SALESFORCE_USERNAME: "40",
    SALESFORCE_PASSWORD: "41",
    SALESFORCE_SECURITY_TOKEN: "42",
    REDSHIFT_CLUSTER_ID: "14",
    REDSHIFT_DATABASE: "15",
    REDSHIFT_JDBC_URL: "16",
    REDSHIFT_USERNAME: "17",
    REDSHIFT_PASSWORD: "50",
    REDSHIFT_CLUSTER_REGION: "18",
    REDSHIFT_IAM_ACCESS_KEY_ID: "19",
    REDSHIFT_IAM_SECRET_ACCESS_KEY: "20",
    DBT_REPO_LATEST_COMMIT_ID: "46",
    CLICKHOUSE_CONNECTION_URL: "47",
    CLICKHOUSE_USERNAME: "48",
    CLICKHOUSE_PASSWORD: "49",
    CLICKHOUSE_DATABASE: "51",
    SLACK_ACCESS_TOKEN: "12",
    SLACK_ERROR_CHANNEL: "13",
    GOOGLE_EMAIL: "54",
    GOOGLE_ACCESS_TOKEN: "52",
    GOOGLE_ID_TOKEN: "55",
    GOOGLE_REFRESH_TOKEN: "53"
}

export default ProviderParameterDefinitionId;

